In [1]:
import sys
sys.path.append('../..')

In [2]:
import pandas as pd
from utils.patternDiscovery import mineRules

In [9]:
pos_nn = pd.read_csv('experiment-results/positives_nn_onlytrain_hybrid.csv')
negatives = pd.read_csv('../../Structured/Beer/train_negatives.csv')
ass_rules_onBeerName = mineRules(pos_nn,negatives,'Beer_Name',min_confidence=0.8,min_support=0.1)
ass_rules_onBeerName.shape

(432, 11)

In [10]:
ass_rules_onBeerName.head()

         antecedents consequents  ...  antecedents_isleft  consequents_isright
0            (L_Ale)     (R_Ale)  ...                True                 True
8          (L_Amber)     (R_Ale)  ...                True                 True
10         (L_Amber)   (R_Amber)  ...                True                 True
11  (L_Ale, L_Amber)     (R_Ale)  ...                True                 True
15  (L_Ale, L_Amber)   (R_Amber)  ...                True                 True

[5 rows x 11 columns]

In [11]:
te = TransactionEncoder()
te_ary = te.fit(transactions).transform(transactions)
df = pd.DataFrame(te_ary, columns=te.columns_)

In [21]:
itemsets_fpg = fpgrowth(df,min_support=0.5,use_colnames=True)

In [22]:
from mlxtend.frequent_patterns import association_rules
ass_rules_all = association_rules(itemsets_fpg,min_threshold=0.8)

In [23]:
ass_rules_all["antecedent_len"] = ass_rules_all["antecedents"].apply(lambda x: len(x))
ass_rules_all['consequent_len'] = ass_rules_all['consequents'].apply(lambda x: len(x))

In [25]:
ass_rules_all[ (ass_rules_all['antecedent_len'] >= 3) & 
                    (ass_rules_all['consequent_len']>= 3)&
       (ass_rules_all['confidence'] > 0.5) ]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedent_len,consequent_len
425,"(L_Ale, R_Imperial, L_Red)","(R_Ale, L_Imperial, R_Red)",0.78125,0.62500,0.625,0.8,1.280000,0.136719,1.875,3,3
426,"(L_Ale, R_Imperial, R_Ale)","(L_Red, L_Imperial, R_Red)",0.78125,0.62500,0.625,0.8,1.280000,0.136719,1.875,3,3
427,"(L_Ale, R_Imperial, R_Red)","(L_Red, R_Ale, L_Imperial)",0.78125,0.62500,0.625,0.8,1.280000,0.136719,1.875,3,3
428,"(L_Ale, R_Imperial, L_Imperial)","(L_Red, R_Ale, R_Red)",0.62500,0.87500,0.625,1.0,1.142857,0.078125,inf,3,3
429,"(L_Ale, L_Imperial, L_Red)","(R_Imperial, R_Red, R_Ale)",0.62500,0.78125,0.625,1.0,1.280000,0.136719,inf,3,3
430,"(L_Ale, R_Ale, L_Imperial)","(L_Red, R_Imperial, R_Red)",0.62500,0.78125,0.625,1.0,1.280000,0.136719,inf,3,3
431,"(L_Ale, L_Imperial, R_Red)","(L_Red, R_Imperial, R_Ale)",0.62500,0.78125,0.625,1.0,1.280000,0.136719,inf,3,3
432,"(L_Red, R_Imperial, R_Ale)","(L_Ale, L_Imperial, R_Red)",0.78125,0.62500,0.625,0.8,1.280000,0.136719,1.875,3,3
433,"(L_Red, R_Imperial, R_Red)","(L_Ale, R_Ale, L_Imperial)",0.78125,0.62500,0.625,0.8,1.280000,0.136719,1.875,3,3
434,"(L_Red, R_Imperial, L_Imperial)","(L_Ale, R_Ale, R_Red)",0.62500,0.87500,0.625,1.0,1.142857,0.078125,inf,3,3
435,"(R_Imperial, R_Red, R_Ale)","(L_Ale, L_Imperial, L_Red)",0.78125,0.62500,0.625,0.8,1.280000,0.136719,1.875,3,3
436,"(R_Imperial, L_Imperial, R_Ale)","(L_Ale, R_Red, L_Red)",0.62500,0.87500,0.625,1.0,1.142857,0.078125,inf,3,3
437,"(R_Imperial, L_Imperial, R_Red)","(L_Ale, R_Ale, L_Red)",0.62500,0.87500,0.625,1.0,1.142857,0.078125,inf,3,3
438,"(L_Red, R_Ale, L_Imperial)","(L_Ale, R_Imperial, R_Red)",0.62500,0.78125,0.625,1.0,1.280000,0.136719,inf,3,3
439,"(L_Red, L_Imperial, R_Red)","(L_Ale, R_Imperial, R_Ale)",0.62500,0.78125,0.625,1.0,1.280000,0.136719,inf,3,3
440,"(R_Ale, L_Imperial, R_Red)","(L_Ale, R_Imperial, L_Red)",0.62500,0.78125,0.625,1.0,1.280000,0.136719,inf,3,3

## Analyze NN calculated only from training set

In [37]:
pos_nn_onlytrain = pd.read_csv('experiment-results/positives_nn_onlytrain_hybrid.csv')
train_neg = pd.read_csv('../../Structured/Beer/train_negatives.csv')
transactions = preProcessNeighbors(pos_nn_onlytrain,train_neg,'Beer_Name')

In [38]:
te = TransactionEncoder()
te_ary = te.fit(transactions).transform(transactions)
df = pd.DataFrame(te_ary, columns=te.columns_)

In [39]:
itemsets_fpmax = fpmax(df,min_support=0.1,use_colnames=True)
itemsets_fpg = fpgrowth(df,min_support=0.2,use_colnames=True)

In [52]:
ass_rules_onlytrain = association_rules(itemsets_fpg,min_threshold=0.8)

In [53]:
ass_rules_onlytrain["antecedent_len"] = ass_rules_onlytrain["antecedents"].apply(lambda x: len(x))
ass_rules_onlytrain['consequent_len'] = ass_rules_onlytrain['consequents'].apply(lambda x: len(x))

In [57]:
ass_rules_onlytrain[ (ass_rules_onlytrain['antecedent_len'] >= 3) & 
                    (ass_rules_onlytrain['consequent_len']>=3)&
       (ass_rules_onlytrain['confidence'] > 0.75) ]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedent_len,consequent_len
398,"(R_Imperial, L_Red, R_Ale)","(R_Red, L_Imperial, L_Ale)",0.338235,0.323529,0.323529,0.956522,2.956522,0.214100,15.558824,3,3
399,"(R_Imperial, L_Red, L_Imperial)","(R_Red, R_Ale, L_Ale)",0.323529,0.514706,0.323529,1.000000,1.942857,0.157007,inf,3,3
400,"(R_Red, R_Imperial, L_Red)","(R_Ale, L_Imperial, L_Ale)",0.338235,0.323529,0.323529,0.956522,2.956522,0.214100,15.558824,3,3
401,"(R_Imperial, L_Red, L_Ale)","(R_Red, R_Ale, L_Imperial)",0.338235,0.323529,0.323529,0.956522,2.956522,0.214100,15.558824,3,3
402,"(R_Imperial, L_Imperial, R_Ale)","(R_Red, L_Red, L_Ale)",0.323529,0.500000,0.323529,1.000000,2.000000,0.161765,inf,3,3
403,"(R_Red, R_Imperial, R_Ale)","(L_Red, L_Imperial, L_Ale)",0.338235,0.323529,0.323529,0.956522,2.956522,0.214100,15.558824,3,3
404,"(R_Imperial, L_Ale, R_Ale)","(R_Red, L_Red, L_Imperial)",0.338235,0.323529,0.323529,0.956522,2.956522,0.214100,15.558824,3,3
405,"(R_Red, R_Imperial, L_Imperial)","(R_Ale, L_Red, L_Ale)",0.323529,0.514706,0.323529,1.000000,1.942857,0.157007,inf,3,3
406,"(R_Imperial, L_Imperial, L_Ale)","(R_Red, R_Ale, L_Red)",0.323529,0.500000,0.323529,1.000000,2.000000,0.161765,inf,3,3
407,"(R_Red, R_Imperial, L_Ale)","(R_Ale, L_Red, L_Imperial)",0.338235,0.323529,0.323529,0.956522,2.956522,0.214100,15.558824,3,3
408,"(R_Ale, L_Red, L_Imperial)","(R_Red, R_Imperial, L_Ale)",0.323529,0.338235,0.323529,1.000000,2.956522,0.214100,inf,3,3
409,"(R_Red, L_Red, L_Imperial)","(R_Imperial, L_Ale, R_Ale)",0.323529,0.338235,0.323529,1.000000,2.956522,0.214100,inf,3,3
410,"(L_Red, L_Imperial, L_Ale)","(R_Red, R_Imperial, R_Ale)",0.323529,0.338235,0.323529,1.000000,2.956522,0.214100,inf,3,3
411,"(R_Red, R_Ale, L_Imperial)","(R_Imperial, L_Red, L_Ale)",0.323529,0.338235,0.323529,1.000000,2.956522,0.214100,inf,3,3
412,"(R_Ale, L_Imperial, L_Ale)","(R_Red, R_Imperial, L_Red)",0.323529,0.338235,0.323529,1.000000,2.956522,0.214100,inf,3,3
413,"(R_Red, L_Imperial, L_Ale)","(R_Imperial, L_Red, R_Ale)",0.323529,0.338235,0.323529,1.000000,2.956522,0.214100,inf,3,3